# Generated by Django 5.1.3 on 2024-12-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0002_appointment_medical_records_appointment_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='calendar_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
