# Generated by Django 5.1.3 on 2024-12-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0004_remove_appointment_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True),
        ),
    ]
