# Generated by Django 5.1.3 on 2024-12-06 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0005_appointment_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hmsapp.appointment'),
        ),
    ]
