# Generated by Django 5.1.3 on 2024-12-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0009_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('INSURANCE', 'Insurance'), ('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI Payment')], max_length=20),
        ),
    ]
